# Meta Data for SEO

## Homepage
title = "Yalink"
titleSeparator = "-"
titleAddition = "Yalink Docs & Blog"
description = "Yalink Docs & Blog est le site de documentation et le blog de Yalink!"

## Open Graph + Twitter Cards
images = [""]
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-yalink.png"
schemaTwitter = "https://twitter.com/henkverlinde"
schemaLinkedIn = "https://www.linkedin.com/in/henkverlinde/"
schemaGitHub = "https://github.com/h-enk"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Construit avec des 💛 par <a href=\"https://yalink.fr/\">Yalink</a> avec l'aide de <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, et <a href=\"https://getdoks.org/\">Doks</a>"

# Alert
alert = false
alertText = "Like Doks? <a class=\"alert-link\" href=\"https://github.com/h-enk/doks/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/h-enk/doks"
editPage = false
