---
label: Blog Post with Image
hide_body: false
fields:
- type: list
  name: contributors
  label: contributors
- type: datetime
  name: date
  label: date
- type: text
  name: description
  label: description
- type: datetime
  name: lastmod
  label: lastmod
- type: text
  name: lead
  label: lead
- type: text
  name: title
  label: title
- name: seotitle
  type: text
  config:
    required: false
  label: Titre seo
  description: Le titre SEO qui apparait dans la section head HTML
- name: url
  type: text
  config:
    required: false
  label: URL
  description: Defines a specific URL (for SEO refined use)
- type: file
  name: imageCover
  label: imageCover
- type: number
  name: weight
  label: weight
pages:
- content/blog/EURL/que-faut-il-connaitre-avant-de-creer-son-eurl-yalink.md
- content/blog/L'entretien/comment-reussir-son-entretien-en-tant-qu-ingenieur.md
- content/blog/La lettre de motivation d'ingénieur/comment-ecrire-une-lettre-de-motivation-pour-un-ingenieur.md
- content/blog/La lettre de motivation d'ingénieur/la-lettre-de-motivation-est-elle-toujours-d-actualite-pour-les-ingenieurs.md
- content/blog/La lettre de motivation d'ingénieur/les-fautes-les-plus-frequentes-a-eviter-a-tout-prix-dans-sa-lettre-de-motivation.md
- content/blog/La lettre de motivation d'ingénieur/pourquoi-la-lettre-de-motivation-n-est-pas-obligatoire-pour-un-ingenieur.md
- content/blog/La lettre de motivation d'ingénieur/quelle-est-l-importance-des-soft-skills-pour-un-ingenieur.md
- content/blog/La lettre de motivation d'ingénieur/quelle-est-la-meilleure-methode-pour-reussir-sa-lettre-de-motivation.md
- content/blog/La lettre de motivation d'ingénieur/quels-logiciels-utiliser-pour-sa-lettre-de-motivation.md
- content/blog/La micro entreprise/comment-devenir-ingenieur-micro-entrepeneur.md
- content/blog/La micro entreprise/micro-entreprise-et-tva-tout-savoir.md
- content/blog/Le Currciculum Vitae/comment-ecrire-un-cv-pour-un-ingenieur.md
- content/blog/Le Currciculum Vitae/comment-optimiser-son-profil-linkedin-pour-l-utiliser-comme-cv.md
- content/blog/Le Currciculum Vitae/les-astuces-d-un-cv-reussi-pour-un-ingenieur.md
- content/blog/Le portage salarial /pourquoi-passer-par-le-portage-salarial.md
- content/blog/bases-freelancing/quelles-sont-les-bases-du-freelancing.md
