---
label: blog post
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: textarea
  name: description
  label: description
- type: textarea
  name: lead
  label: lead
- type: datetime
  name: date
  label: date
- type: datetime
  name: lastmod
  label: lastmod
- type: number
  name: weight
  label: weight
- type: image_gallery
  name: images
  label: images
- type: list
  name: contributors
  label: contributors
