---
label: Contributor
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: description
  label: description
- type: datetime
  name: date
  label: date
- type: datetime
  name: lastmod
  label: lastmod
- type: list
  name: images
  label: images
pages:
- content/contributors/Antoine/antoine-paemelaere.md
